version: '3.1'

services:
  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
