GET localhost:8080

GET localhost:8080/todos

POST localhost:8080/todos
Content-Type: application/json

{
	"title": "title",
	"description": "description"
}

PUT localhost:8080/todos
Content-Type: application/json

{
	"id": "fddefb57-9dcc-4028-b316-3912617649d9",
	"title": "updated title",
	"description": "updated description"
}

DELETE localhost:8080/todos
Content-Type: application/json

{
	"id": "fddefb57-9dcc-4028-b316-3912617649d9"
}
