GET localhost:8080

// Todo
GET localhost:8080/todo
Cookie: token=pass

POST localhost:8080/todo
Content-Type: application/json

{
	"title": "title",
	"description": "description"
}

PUT localhost:8080/todo/c2a935b9-5d26-4b91-a107-a76629e76881
Content-Type: application/json

{
	"title": "updated title",
	"description": "updated description"
}

DELETE localhost:8080/todo/9ded44d7-d3f2-4664-bcd0-6e018f70d923

// Auth
POST localhost:8080/auth/signup
Content-Type: application/json

{
	"name": "steve",
	"password": "15"
}

### 

POST localhost:8080/auth/signin
Content-Type: application/json

{
	"name": "steve",
	"password": "15"
}

###

DELETE localhost:8080/auth/signout

